#!/usr/bin/env python3
# -*- coding=utf-8 -*-

"""
NAME
	mdwc_ - Molecular Dynamics With Constraints

DESCRIPTION
        The molecular dynamics with constraints (mdwc) package is a 
	command line open source python program. It does constraint 
	molecular dynamics following the SHAKE algorithm with:

   	    - NPT: keeping pressure constant with the Parrinello- 
          	   Rahman lagrangian, and keeping the temperature 
		   constant with the Nose thermostat) 

   	    - NVT: keeping the temperature constant with the Nose 
                   thermostat. 

	Allowed constraints:
   	    - bond distances
   	    - angles
   	    - atomic positions
   	    - lattice parameters (a, b, c)
   	    - angles between lattice vectors
   	    - volume of the unit cell

	Supported DFT codes:
	    - Abinit
            - ...

SYNTAX
	mdwc_ <sub-command> [OPTIONS]

SUB-COMMANDS

   # ----- Help ----------------------------------

        -h, -help
	    print this help

   # ----- Files Manager -------------------------

	-n, --name [NAME]

   # ----- Molecular Dynamics Manager ------------

        -npt
            Run NPT Molecular Dynamics (default)

	-nvt
	    Run NVT Molecular Dynamics

   # ----- MPI -----------------------------------

	-np, --ntasks [NUMBER_OF_TASKS]
	    Number of tasks for mpi parallelization

	-mopt, --mpi_options "[OPTIONS]"
	    Add more options for mpirun

REQUIREMENTS
	- Python 3
	- Numpy >= 1.1 1
	- DFT Code 

LINKS
        GitHub - https://github.com/romerogroup/mdwc.git
        Documentation - https://molecular-dynamics-with-constraints.github.io/

MAINTAINER
        Prof. Romero, Aldo H. (Aldo.Romero@mail.wvu.edu)

CONTRIBUTORS
        Prof. Romero, Aldo H.  -  West Virginia University 
        Hernandez, Arturo      -  West Virginia University 
        Herath, Uthpala        -  West Virginia University 
        Tavazohi, Pedram       -  West Virginia University 

"""

from __future__ import division, print_function
from mdwc.core.manager import main

if __name__ == "__main__":
	main()

